CREATE TABLE notifications (
    id BIGINT PRIMARY KEY,
    message VARCHAR(255) NOT NULL,
    order_id BIGINT,
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
